apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-alert-system-alert-dispatcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-dispatcher-service
  template:
    metadata:
      labels:
        app: alert-dispatcher-service
    spec:
      containers:
        - name: alert-dispatcher-service
          image: go-alert-system-alert-dispatcher-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: go-alert-system-alert-dispatcher-service
spec:
  selector:
    app: alert-dispatcher-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: NodePort
