apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-api
  template:
    metadata:
      labels:
        app: metrics-api
    spec:
      containers:
        - name: metrics-api
          image: metrics-api-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: metrics-api-service
spec:
  selector:
    app: metrics-api
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: NodePort
