apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-alert-system-rule-engine-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rule-engine-service
  template:
    metadata:
      labels:
        app: rule-engine-service
    spec:
      containers:
        - name: rule-engine-service
          image: go-alert-system-rule-engine-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003

---
apiVersion: v1
kind: Service
metadata:
  name: go-alert-system-rule-engine-service
spec:
  selector:
    app: rule-engine-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: NodePort
