apiVersion: apps/v1
kind: Deployment
metadata:
  name: rule-management-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rule-management-api
  template:
    metadata:
      labels:
        app: rule-management-api
    spec:
      containers:
        - name: rule-management-api
          image: rule-management-api-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8004

---
apiVersion: v1
kind: Service
metadata:
  name: rule-management-api-service
spec:
  selector:
    app: rule-management-api
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
  type: NodePort
