apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-alert-system-rule-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rule-management-service
  template:
    metadata:
      labels:
        app: rule-management-service
    spec:
      containers:
        - name: rule-management-service
          image: go-alert-system-rule-management-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8004

---
apiVersion: v1
kind: Service
metadata:
  name: go-alert-system-rule-management-service
spec:
  selector:
    app: rule-management-service
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
  type: ClusterIP
